/* Annual decisions and the records passed down by each school generation. */
(function(root){
  'use strict';
  root.TrackCareerUI={create};
  function create({E,esc,icon}){
    let tab='season';
    const tabs=[['season','今年の挑戦'],['records','学校記録'],['alumni','卒業生名鑑'],['seasons','年度の歩み']];
    const eventName=id=>E.EVENTS.find(e=>e.id===id)?.name||id;
    const genderName=g=>g==='girls'?'女子':'男子';
    const modeName=id=>E.CAREER_MODES.find(m=>m.id===id)?.name||'通常';
    const goalName=id=>id?E.CAREER_GOALS.find(g=>g.id===id)?.name||id:'保存済みの大会記録';
    const progress=c=>Math.min(100,Math.round(c.goal.current/c.goal.target*100));
    function banner(state){
      const c=E.getCareer(state);
      return `<section class="career-banner ${c.goal.achieved?'achieved':''}"><div class="career-banner-symbol">${icon(c.goal.achieved?'trophy':'flag')}</div><div><span class="career-eyebrow">創部${state.year}年目の挑戦 · ${esc(c.mode.name)}</span><strong>${esc(c.goal.name)}</strong><p>${c.goal.achieved?`達成！ 設備の整備機会を1回追加${c.goal.rewarded?'':'予定'}`:`進捗 ${c.goal.current} / ${c.goal.target}${c.canChangeGoal?' · 4月1週は目標を選べます':''}`}</p></div><button class="btn small" data-action="navigate" data-page="career">今年の目標を見る ${icon('arrow')}</button></section>`;
    }
    function season(state,c){
      return `<section class="panel legacy-current"><div class="legacy-current-heading"><div><span class="career-eyebrow">THIS YEAR'S CHALLENGE</span><h2>${esc(c.goal.name)}</h2><p>${esc(c.goal.description)}</p></div><strong class="legacy-progress-number">${c.goal.current}<small> / ${c.goal.target}</small></strong></div><div class="progress-track"><div class="progress-fill" style="width:${progress(c)}%"></div></div><div class="legacy-progress-caption"><span>${c.goal.achieved?(c.goal.rewarded?'目標達成、おめでとう！':'達成済み。整備機会は次の大会後、または年度末に追加。'):'3月4週まで、今年の仲間と挑もう。'}</span><strong>${c.goal.rewarded?'整備機会 +1回':c.goal.achieved?'整備機会 追加予定':'達成で設備の整備 +1回'}</strong></div></section>
      <div class="section-title"><h2>${icon('star')}今年の目標を選ぶ</h2><span class="subtext">${c.canChangeGoal?'4月1週の間は変更できます':'次の4月1週に選び直せます'}</span></div><div class="legacy-goals">${E.CAREER_GOALS.map(g=>`<article class="legacy-goal ${c.season.goalId===g.id?'selected':''}"><span class="tag">${c.season.goalId===g.id?'今年の目標':'挑戦目標'}</span><h3>${esc(g.name)}</h3><p>${esc(g.description)}</p><div><span>達成で整備 +1回</span><button class="btn small ${c.season.goalId===g.id?'green':''}" data-action="season-goal" data-id="${g.id}" ${!c.canChangeGoal||c.season.goalId===g.id?'disabled':''}>${c.season.goalId===g.id?'選択中':'この目標にする'}</button></div></article>`).join('')}</div>
      <div class="section-title"><h2>${icon('flag')}大会のモード</h2></div><div class="legacy-modes">${E.CAREER_MODES.map(m=>`<article class="panel legacy-mode ${c.season.mode===m.id?'selected':''}"><h3>${esc(m.name)}</h3><p>${m.id==='challenge'?'地区から強豪校と競い、全国ではさらに高い水準に挑みます。疲労管理・育成・走順で、わずかな差をつくろう。':'12人の創部から全国へ。育成と世代交代を楽しみながら、学校の歴史を育てる基本モードです。'}</p><button class="btn small ${c.season.mode===m.id?'green':''}" data-action="season-mode" data-id="${m.id}" ${!c.canChangeMode||c.season.mode===m.id?'disabled':''}>${c.season.mode===m.id?'このモードで進行中':'このモードにする'}</button></article>`).join('')}</div><p class="legacy-footnote">目標とモードは毎年4月1週に選び、1週進めるとその年度の間は固定されます。達成報酬は1年度に1回。部員・施設・セーブを引き継いで次の年度へ進みます。</p>`;
    }
    function records(state,c){
      return `<div class="page-intro">${icon('flag')}正式出場で残した学校最高記録。男女とハードルの高さごとに記録し、保持者が卒業しても残ります。</div>${c.schoolRecords.length?['boys','girls'].map(g=>`<div class="section-title"><h2>${genderName(g)}の学校記録</h2></div><div class="legacy-records">${c.schoolRecords.filter(r=>r.gender===g).map(r=>`<article class="legacy-record"><div class="legacy-record-event"><strong>${esc(eventName(r.eventId))}</strong>${r.hurdleHeight?`<small>ハードル高 ${Math.round(r.hurdleHeight*1000)/10}cm</small>`:''}<span class="tag">${esc(modeName(r.mode))}</span></div><strong class="legacy-record-value">${E.formatResult(r.value,r.eventId)}</strong><div class="legacy-record-holder"><strong>${esc(r.athleteName)}</strong>${r.members?.length?`<p>${r.members.map(m=>esc(m.name)).join(' → ')}</p>`:''}<small>創部${r.year}年目 · ${esc(r.meetName)}</small></div></article>`).join('')||'<div class="empty small-empty">次の大会で、最初の一行を刻もう。</div>'}</div>`).join(''):'<div class="empty">まだ学校記録はありません。<br>5月の地区予選から、部の歴史が始まります。</div>'}<p class="legacy-footnote">オープン記録会の参考記録は学校記録に含めません。以前のセーブでは、残っている大会履歴から確認できる記録を引き継ぎます。</p>`;
    }
    function alumni(state,c){
      return `<div class="page-intro">${icon('users')}直近60人の卒業生。3年間で育てた能力と記録を、名鑑に残します。</div>${c.alumni.length?`<div class="legacy-alumni">${c.alumni.map(a=>`<article class="panel legacy-alumnus"><div class="legacy-alumnus-header"><canvas class="avatar" data-alumni-avatar="${esc(a.id)}" width="86" height="88" aria-label="${esc(a.name)}のドット絵"></canvas><div><h3>${esc(a.name)}</h3><small>${genderName(a.gender)} · 創部${a.graduationYear}年目の卒業生</small><p>${esc(a.trait)} · ${esc(eventName(a.event))}</p></div></div><div class="legacy-alumni-stats">${E.STAT_KEYS.map(k=>`<div><span>${esc(E.STAT_NAMES[k])}</span><strong>${Math.floor(E.getStat(a,k))}</strong></div>`).join('')}</div><details><summary>卒業時の自己記録を見る</summary><div class="legacy-personal-records">${Object.entries(a.bestBySpec).map(([key,v])=>{const [id,height]=key.split(':');return `<p><span>${esc(eventName(id))}${height?` (${Math.round(Number(height)*1000)/10}cm)`:''}</span><strong>${E.formatResult(v,id)}</strong></p>`;}).join('')||'<p>大会記録なし。練習で後輩たちを支えました。</p>'}</div></details></article>`).join('')}</div>`:'<div class="empty">最初の卒業は、創部3年目の3月末。<br>12人の1年生と過ごす日々を、大切に。</div>'}<p class="legacy-footnote">名鑑に載るのは記録機能の追加後に卒業した選手です。古い名鑑が一覧から外れても、累計卒業人数と学校記録は残ります。</p>`;
    }
    function seasons(state,c){
      return `<div class="page-intro">${icon('calendar')}毎年の挑戦と成績を振り返ります。直近30年の要約と、累計実績を保存します。</div>${c.seasons.length?`<div class="legacy-seasons">${c.seasons.map(s=>`<article class="panel legacy-season"><div class="legacy-season-year"><strong>${s.year}</strong><span>年目</span><span class="tag">${esc(modeName(s.mode))}</span></div><div><h3>${esc(goalName(s.goalId))}</h3><p class="${s.achieved?'legacy-success':''}">${s.partial?'残っている大会履歴から復元した成績':s.achieved?'目標達成 · 次の世代へ設備を継承':'次の世代へ挑戦をつなぐ'}</p><p>金 ${s.medals.gold} · 銀 ${s.medals.silver} · 銅 ${s.medals.bronze}</p><small>自己ベスト ${s.personalBests}回 · インターハイ優勝 ${s.interhighWins}種目 · ${s.meetCount}大会</small></div></article>`).join('')}</div>`:'<div class="empty">1年の締めくくりは、3月の最終週。<br>今年の物語は、ここから続いていきます。</div>'}<p class="legacy-footnote">年度の区切りは4月から翌3月。インターハイで1種目以上優勝した年度を優勝年度として数え、連続する年度を連覇として記録します。</p>`;
    }
    function render(state){
      const c=E.getCareer(state),l=c.lifetime;
      return `<section class="legacy-hero"><div><span class="career-eyebrow">THE STORY CONTINUES</span><h2>この部活の物語は、<br>次の世代へ続いていく。</h2><p>新しい目標、新しい仲間。<br>今年は、どんな一年にしよう。</p></div><div class="legacy-totals">${[['達成した年度目標',l.goalsAchieved,'回'],['IH優勝年度',l.interhighTitles,'年'],['最高連覇',l.bestStreak,'連覇'],['送り出した卒業生',l.graduates,'人']].map(([label,n,unit])=>`<div><span>${label}</span><strong>${n}<small>${unit}</small></strong></div>`).join('')}</div></section><div class="legacy-tabs" role="group" aria-label="部の歴史の表示">${tabs.map(([id,name])=>`<button data-action="career-tab" data-id="${id}" aria-pressed="${id===tab}" class="${id===tab?'active':''}">${name}</button>`).join('')}</div><div data-career-content="${tab}">${({season,records,alumni,seasons}[tab])(state,c)}</div><p class="legacy-footnote">この記録機能は創部${c.startedYear}年目から利用。以前のセーブに残る大会結果も反映しますが、既に消えた大会の成績や卒業生は復元できません。</p>`;
    }
    function draw(state){const alumni=E.getCareer(state).alumni;for(const canvas of document.querySelectorAll('[data-alumni-avatar]')){const a=alumni.find(a=>a.id===canvas.dataset.alumniAvatar);if(a)root.TrackScene.drawPortrait(canvas,a);}}
    return {banner,render,draw,setTab(id){if(tabs.some(([key])=>key===id))tab=id;}};
  }
})(typeof globalThis!=='undefined'?globalThis:this);
